// Sample data for the gallery
        const galleryData = [
            {
                title: "Fullstack Developer Porfolio",
                description: "Full-Stack Developer crafting digital experiences through clean code and thoughtful design",
                creator: "Blessing ",
                creatorTitle: "Developer",
                // creatorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=80",
                mediaType: "website",
                mediaUrl: "https://hongshin-showcase.lovable.app/",
                aiTools: ["Lovable"]
            },
            {
                title: "Future City Timelapse",
                description: "A futuristic cityscape animated with AI, showing a day-to-night transition with flying vehicles.",
                creator: "Maya Chen",
                creatorTitle: "Digital Animator",
                creatorImg: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=80",
                mediaType: "video",
                mediaUrl: "https://www.youtube.com/embed/7NN4FFlWX4w",
                aiTools: ["HeyGen", "Runway ML", "After Effects"]
            },
            {
                title: "AI Assistant Dashboard",
                description: "An interactive dashboard for managing AI assistants across multiple platforms with real-time analytics.",
                creator: "David Kim",
                creatorTitle: "UI/UX Designer",
                creatorImg: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=80",
                mediaType: "website",
                mediaUrl: "https://example.com",
                aiTools: ["ChatGPT", "Canva", "Figma AI"]
            },
            {
                title: "Cosmic Dreams",
                description: "A surreal space scene with nebulas and planets that don't exist in our universe, created with AI.",
                creator: "Sarah Williams",
                creatorTitle: "Digital Artist",
                creatorImg: "https://images.unsplash.com/photo-1558898479-33c0057a5d12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=80",
                mediaType: "image",
                mediaUrl: "https://images.unsplash.com/photo-1670272504522-38e2537d917d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
                aiTools: ["Stable Diffusion", "Krea", "DALL-E"]
            },
            {
                title: "AI Product Tutorial",
                description: "A tutorial video explaining how to use the latest AI design tools to improve workflow.",
                creator: "TechGuide",
                creatorTitle: "Education Channel",
                creatorImg: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=80",
                mediaType: "video",
                mediaUrl: "https://www.youtube.com/embed/7NN4FFlWX4w",
                aiTools: ["HeyGen", "ChatGPT", "Canva"]
            },
            {
                title: "Neural Art Gallery",
                description: "An online gallery showcasing art generated by neural networks from around the world.",
                creator: "AI Art Collective",
                creatorTitle: "Art Organization",
                creatorImg: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=80",
                mediaType: "website",
                mediaUrl: "https://example.com",
                aiTools: ["ChatGPT", "Midjourney", "Webflow AI"]
            }
        ];

        // Function to generate gallery cards
        function generateGalleryCards(data) {
            const gallery = document.getElementById('gallery');
            gallery.innerHTML = '';
            
            data.forEach(item => {
                let mediaContent = '';
                if (item.mediaType === 'image') {
                    mediaContent = `
                        <img src="${item.mediaUrl}" alt="${item.title}" class="w-full h-full object-cover">
                        <span class="absolute top-4 right-4 bg-black/70 px-3 py-1 rounded-full text-xs">Image</span>
                    `;
                } else if (item.mediaType === 'video') {
                    mediaContent = `
                        <iframe src="${item.mediaUrl}" class="w-full h-full" frameborder="0" allowfullscreen></iframe>
                        <span class="absolute top-4 right-4 bg-black/70 px-3 py-1 rounded-full text-xs">Video</span>
                    `;
                } else if (item.mediaType === 'website') {
                    mediaContent = `
                        <div class="w-full h-full bg-gray-100 flex flex-col items-center justify-center text-gray-800">
                            <i class="fas fa-globe text-4xl mb-2"></i>
                            <span class="text-sm font-medium">Website Preview</span>
                        </div>
                        <span class="absolute top-4 right-4 bg-black/70 px-3 py-1 rounded-full text-xs">Website</span>
                    `;
                }
                
                const card = document.createElement('div');
                card.className = 'bg-blue-900/30 backdrop-blur-md rounded-xl overflow-hidden border border-blue-700/30 card-hover';
                card.dataset.type = item.mediaType;
                card.dataset.tools = item.aiTools.map(tool => tool.toLowerCase()).join(' ');
                
                card.innerHTML = `
                    <div class="h-56 overflow-hidden relative media-container">
                        ${mediaContent}
                    </div>
                    <div class="p-5">
                        <h3 class="text-xl font-semibold mb-2">${item.title}</h3>
                        <p class="text-blue-100 mb-4">${item.description}</p>
                        <div class="flex items-center mb-4">
                            <img src="${item.creatorImg}" alt="${item.creator}" class="w-10 h-10 rounded-full mr-3">
                            <div>
                                <p class="font-medium">${item.creator}</p>
                                <p class="text-sm text-blue-200">${item.creatorTitle}</p>
                            </div>
                        </div>
                        <div class="flex flex-wrap gap-2">
                            ${item.aiTools.map(tool => `<span class="bg-blue-600/20 text-blue-200 px-3 py-1 rounded-full text-sm">${tool}</span>`).join('')}
                        </div>
                    </div>
                `;
                
                gallery.appendChild(card);
            });
        }

        // Initialize the gallery
        generateGalleryCards(galleryData);

        // Search and filter functionality
        const searchInput = document.getElementById('searchInput');
        const filterButtons = document.querySelectorAll('.filter-btn');
        
        // Add event listener for search input
        searchInput.addEventListener('input', function() {
            filterGallery();
        });
        
        // Add event listeners for filter buttons
        filterButtons.forEach(button => {
            button.addEventListener('click', function() {
                filterButtons.forEach(btn => {
                    btn.classList.remove('active');
                    btn.classList.remove('bg-blue-600');
                    btn.classList.add('bg-blue-900/40');
                });
                this.classList.add('active');
                this.classList.remove('bg-blue-900/40');
                this.classList.add('bg-blue-600');
                filterGallery();
            });
        });
        
        // Function to filter the gallery
        function filterGallery() {
            const searchTerm = searchInput.value.toLowerCase();
            const activeFilter = document.querySelector('.filter-btn.active').dataset.filter;
            
            const filteredData = galleryData.filter(item => {
                // Check if item matches search term
                const matchesSearch = 
                    item.title.toLowerCase().includes(searchTerm) ||
                    item.description.toLowerCase().includes(searchTerm) ||
                    item.creator.toLowerCase().includes(searchTerm) ||
                    item.aiTools.some(tool => tool.toLowerCase().includes(searchTerm));
                
                // Check if item matches filter
                let matchesFilter = true;
                if (activeFilter !== 'all') {
                    if (['image', 'video', 'website'].includes(activeFilter)) {
                        matchesFilter = item.mediaType === activeFilter;
                    } else {
                        matchesFilter = item.aiTools.some(tool => 
                            tool.toLowerCase().includes(activeFilter));
                    }
                }
                
                return matchesSearch && matchesFilter;
            });
            
            generateGalleryCards(filteredData);
        }
